```{r}
library(readr)
library(dplyr)
library(tmap)
library(sf)
```

```{r}
rose_sf <- sf::st_read('../data/raw/rose_garden.geojson')
expo_sf <- sf::st_read('../data/raw/expo_park.geojson')
nhm_sf <- sf::st_read('../data/raw/nhm.geojson')

```

```{r}
rose_map <-  tm_shape(rose_sf) +
  tm_borders(col='#3333cc', lwd=2)
rose_map
```


```{r}
expo_map <-  tm_shape(expo_sf) +
  tm_borders(col='#cccccc', lwd=2)
expo_map
```

```{r}
nhm_map <-  tm_shape(nhm_sf) +
  tm_borders(col='#cc0000', lwd=2)
nhm_map
```
```{r}
# https://r-tmap.github.io/tmap/articles/basics_basemaps

# names(leaflet::providers)
```

```{r}
# https://jakob.schwalb-willmann.de/basemaps/reference/basemap.html#ref-examples
#get_maptypes()
```


```{r}
tmap_mode("view")

expo_map + nhm_map + rose_map + tm_basemap(server = "Esri.WorldImagery")
```
```{r}
tmap_mode("plot")

expo_map + nhm_map +  rose_map + tm_basemap(server = "Esri.WorldImagery")
```
```{r}
tmap_mode("view")

c <- rbind(nhm_sf, rose_sf)
a<- st_bbox( c)
b <- st_as_sfc(a)

tm_shape(b) + 
  tm_borders() +
  tm_basemap( )
```
```{r}
tm_shape(nhm_sf) + 
  tm_fill() +
  tm_shape(rose_sf) + 
  tm_fill() +
  tm_shape(gbif_sf) + 
  tm_markers()
```

