```{r}
library(readr)
library(dplyr)
library(rgbif)
library(taxize)
library(tidyverse)

```
```{r}
taxa <- c('Apis mellifera','Sciurus niger')

rgbif::name_backbone_checklist(taxa) 
```

```{r}
common_names <- taxize::sci2comm(sci=taxa, db='ncbi')
```
## top ten species

```{r}
#| message: false
gbif_df <- read_csv('../data/processed/gbif_gardens.csv')

gbif_nhm_df <- gbif_df |>
  filter(place == 'NHMLAC')

gbif_rose_df <- gbif_df |>
  filter(place == 'Rose Garden')
```

```{r}
top_10_nhm_inat <- gbif_nhm_df |> 
  filter(institutionCode=='iNaturalist') |>
  count(class, verbatimScientificName) |>
  arrange(desc(n)) |>
  slice(1:10)

top_10_rose_inat <- gbif_rose_df |> 
  filter(institutionCode=='iNaturalist') |>
  count(class, verbatimScientificName) |>
  arrange(desc(n)) |>
  slice(1:10)

top_10_nhm <- gbif_nhm_df |> 
  count(class, verbatimScientificName) |>
  arrange(desc(n)) |>
  slice(1:10)

top_10_rose <- gbif_rose_df |> 
  count(class, verbatimScientificName) |>
  arrange(desc(n)) |>
  slice(1:10)
```
```{r}
taxa <- unique(c(top_10_nhm$verbatimScientificName,
          top_10_rose$verbatimScientificName,
          top_10_nhm_inat$verbatimScientificName,
          top_10_rose_inat$verbatimScientificName
          ))

taxa
```

https://docs.ropensci.org/taxize/reference/sci2comm.html

 Data source, one of "ncbi" (default), "itis" "eol", "worms", or "iucn"
 
```{r}

common_names <- taxize::sci2comm(sci=taxa, db='ncbi' )
```
 
 
```{r}
# https://stackoverflow.com/a/54099825
# for (name in names(common_names)) {
#     print(name)
#     print(common_names[[name]])
# }
```

 
```{r}
# unlist(common_names, use.names = F)
```

```{r}
# unlist(common_names, use.names = T)
```
 
```{r}
# https://stackoverflow.com/a/57505534


names_df <- enframe(common_names) %>%
   unnest

names_df
```
```{r}
write_csv(names_df, '../data/processed/ncbi_common_names.csv')
```

